//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.BancoDeDados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FarmaciaEntities : DbContext
    {
        public FarmaciaEntities()
            : base("name=FarmaciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_clientes_farmacia> tb_clientes_farmacia { get; set; }
        public virtual DbSet<tb_produtos_farmacia> tb_produtos_farmacia { get; set; }
        public virtual DbSet<tb_produtos_vendidos_farmacia> tb_produtos_vendidos_farmacia { get; set; }
        public virtual DbSet<tb_usuario_perfil_farmacia> tb_usuario_perfil_farmacia { get; set; }
        public virtual DbSet<tb_usuarios_farmacia> tb_usuarios_farmacia { get; set; }
    }
}
