//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Farmacia.BancoDeDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_produtos_vendidos_farmacia
    {
        public int id_produto_vendido { get; set; }
        public Nullable<int> id_produto { get; set; }
        public Nullable<int> id_cliente { get; set; }
        public Nullable<System.DateTime> data_venda { get; set; }
        public Nullable<int> in_quantidade_vendido { get; set; }
        public Nullable<decimal> valor_total { get; set; }
    
        public virtual tb_clientes_farmacia tb_clientes_farmacia { get; set; }
        public virtual tb_produtos_farmacia tb_produtos_farmacia { get; set; }
    }
}
